# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 401)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 380))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background: rgb(248, 248, 248)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.lemm_input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lemm_input_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setUnderline(False)
        self.lemm_input_line.setFont(font)
        self.lemm_input_line.setStyleSheet("QLineEdit {\n"
"    background: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-width: 3px;\n"
"}")
        self.lemm_input_line.setObjectName("lemm_input_line")
        self.verticalLayout_3.addWidget(self.lemm_input_line)
        self.attributes_layout = QtWidgets.QHBoxLayout()
        self.attributes_layout.setObjectName("attributes_layout")
        self.nsubj_input_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nsubj_input_line.sizePolicy().hasHeightForWidth())
        self.nsubj_input_line.setSizePolicy(sizePolicy)
        self.nsubj_input_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.nsubj_input_line.setFont(font)
        self.nsubj_input_line.setStyleSheet("QLineEdit {\n"
"    background: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-width: 3px;\n"
"}")
        self.nsubj_input_line.setObjectName("nsubj_input_line")
        self.attributes_layout.addWidget(self.nsubj_input_line, 0, QtCore.Qt.AlignTop)
        self.gender_input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.gender_input_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.gender_input_line.setFont(font)
        self.gender_input_line.setStyleSheet("QLineEdit {\n"
"    background: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-width: 3px;\n"
"}")
        self.gender_input_line.setObjectName("gender_input_line")
        self.attributes_layout.addWidget(self.gender_input_line, 0, QtCore.Qt.AlignTop)
        self.tense_input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.tense_input_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tense_input_line.setFont(font)
        self.tense_input_line.setStyleSheet("QLineEdit {\n"
"    background: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-width: 3px;\n"
"}")
        self.tense_input_line.setObjectName("tense_input_line")
        self.attributes_layout.addWidget(self.tense_input_line, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addLayout(self.attributes_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 45))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(242, 242, 242);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(217, 217, 217);\n"
"    margin: 2px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.delemmatized_output_line = QtWidgets.QLineEdit(self.centralwidget)
        self.delemmatized_output_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.delemmatized_output_line.setFont(font)
        self.delemmatized_output_line.setStyleSheet("QLineEdit {\n"
"    background: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: rgb(115, 115, 115);\n"
"    border-radius: 5px;\n"
"}")
        self.delemmatized_output_line.setReadOnly(True)
        self.delemmatized_output_line.setPlaceholderText("")
        self.delemmatized_output_line.setObjectName("delemmatized_output_line")
        self.verticalLayout_3.addWidget(self.delemmatized_output_line)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.main_layout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Де-лемматизатор предложений"))
        self.lemm_input_line.setPlaceholderText(_translate("MainWindow", "Лемматизированное предложение"))
        self.nsubj_input_line.setPlaceholderText(_translate("MainWindow", "Подлежащее"))
        self.gender_input_line.setPlaceholderText(_translate("MainWindow", "Род подлежащего"))
        self.tense_input_line.setPlaceholderText(_translate("MainWindow", "Время"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать"))
        self.label.setText(_translate("MainWindow", "Де-лемматизированное предложение"))
